version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./api:/app/
    links:
      - php

  php:
    build: 
      context: .
      dockerfile: Docker/php/Dockerfile
    volumes:
      - ./api:/app/
    
  app:
    build:
      context: .
      dockerfile: Docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/:/usr/app
      - /usr/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    